import React, { useState } from 'react';
import { Alert, Badge, Button, Group, Paper, Stack, Text, Textarea, Title } from '@mantine/core';
import { IconArrowUp, IconArrowUpRight, IconCheck, IconCopy, IconInfoCircle, IconQuote, IconSparkles } from '@tabler/icons-react';
import { PageTitle, SourceIcon } from './shared.jsx';
import s from './workspace.module.css';

const evidence = [
  { type: 'Document', name: 'Atlas launch brief.pdf', location: 'Page 4 · Launch experience', text: 'The first session should produce a useful answer. Make source readiness visible and give people a clear starting point.' },
  { type: 'Audio', name: 'Customer interview — Maya', location: '02:14–02:38 · Conversation', text: 'What would help me most is three or four suggested questions based on what I just uploaded. I do not want to start with a blank page.' },
  { type: 'YouTube', name: 'Product walkthrough', location: '01:32–01:58 · Video transcript', text: 'Open the evidence alongside the answer so you can check the source without losing your place.' },
];
const initialQuestion = 'What should we prioritize for the Atlas onboarding experience?';

export default function Ask({ notify }) {
  const [question, setQuestion] = useState('');
  const [selected, setSelected] = useState(1);
  const [asked, setAsked] = useState(initialQuestion);
  const [view, setView] = useState('answer');
  return <><PageTitle eyebrow="FOLLOW THE EVIDENCE" title="A good question changes things." description="Explore your workspace, with the sources always close by."><Badge variant="light" color="workspace" leftSection={<IconCheck size={13}/>}>4 ready sources</Badge></PageTitle>
    <div className={s.askGrid}><div><Paper className={s.answerPanel}>
      <div className={s.questionBubble}><Text className={s.eyebrow}>YOUR QUESTION</Text><Title order={3} mt="sm">{asked}</Title></div>
      {view === 'empty' ? <div className={s.empty}><IconSparkles size={35}/><Title order={3}>Start with what you want to understand.</Title><Text c="dimmed">Your answer and supporting passages will appear here.</Text></div> : view === 'insufficient' ? <div className={s.answerBody}><Alert color="gray" title="There isn’t enough evidence in this workspace." icon={<IconInfoCircle size={19}/>}>Try a more specific question or add a source with the missing information. We couldn’t find support for this answer.</Alert></div> : <div className={s.answerBody}><Group gap={9} mb="lg"><span className={s.answerMark}><IconSparkles size={17}/></span><Text fw={600}>Workspace answer</Text></Group><Title order={2}>Help people get to a useful first answer.</Title><Text mt="md" lh={1.8}>The research points to three priorities: make the first question easy, show when sources are ready, and let people check the evidence without leaving their answer.</Text><div className={s.answerPoint}><span>01</span><div><Text fw={650}>Offer a starting point</Text><Text lh={1.8} c="dimmed">Use a few relevant example questions to help people move past a blank page. Maya explicitly describes this need in her interview. <button className={s.citation} onClick={() => setSelected(1)} aria-label="Read evidence 2">2</button></Text></div></div><div className={s.answerPoint}><span>02</span><div><Text fw={650}>Make source readiness obvious</Text><Text lh={1.8} c="dimmed">Show clear processing states before people ask. The launch brief makes a useful first answer the central onboarding goal. <button className={s.citation} onClick={() => setSelected(0)} aria-label="Read evidence 1">1</button></Text></div></div><div className={s.answerPoint}><span>03</span><div><Text fw={650}>Keep the evidence within reach</Text><Text lh={1.8} c="dimmed">Open the supporting passage beside the answer and retain its page or timestamp. This helps people verify what they read. <button className={s.citation} onClick={() => setSelected(2)} aria-label="Read evidence 3">3</button></Text></div></div><div className={s.answerTakeaway}><Text fw={600} size="sm">A practical first iteration</Text><Text size="sm" mt={5}>A short starting prompt, clear source status, and an evidence panel alongside every answer.</Text></div><Group justify="space-between" mt="lg"><Text size="xs" c="dimmed">3 supporting passages · Sample answer</Text><Button variant="subtle" size="xs" leftSection={<IconCopy size={14}/>} onClick={() => {navigator.clipboard?.writeText('Help people get to a useful first answer: offer a starting point, show source readiness, and keep evidence within reach.').then(() => notify('Sample answer copied.')).catch(() => notify('Clipboard unavailable in this browser.'));}}>Copy</Button></Group></div>}
    </Paper><Paper className={s.composer}><Textarea label="Ask another question" placeholder="What else would you like to understand?" autosize minRows={2} maxRows={6} value={question} onChange={e => setQuestion(e.target.value)}/><Group justify="space-between" mt="md"><Text size="xs" c="dimmed">Each question searches independently.</Text><Button rightSection={<IconArrowUp size={16}/>} disabled={!question.trim()} onClick={() => {setAsked(question);setQuestion('');setView('insufficient');}}>Ask workspace</Button></Group></Paper><Group mt="sm" gap="xs"><Text size="xs" c="dimmed">Preview states:</Text>{[['answer','Answer'],['empty','Empty'],['insufficient','Insufficient evidence']].map(([id,label]) => <Button size="compact-xs" variant={view === id ? 'light' : 'subtle'} key={id} onClick={() => {setView(id);setAsked(initialQuestion);}}>{label}</Button>)}</Group></div>
    <aside className={s.evidenceAside} aria-label="Supporting evidence"><Paper className={s.evidencePanel}><div className={s.panelHeading}><div><Text className={s.eyebrow}>SEE FOR YOURSELF</Text><Title order={3} mt={5}>Supporting evidence</Title></div><Badge variant="light" color="gray">03</Badge></div><Stack gap={0}>{evidence.map((item,index) => <button key={item.name} className={s.evidenceItem} data-active={selected === index} onClick={() => setSelected(index)}><Group wrap="nowrap" align="flex-start" gap="sm"><SourceIcon type={item.type}/><div><Text size="sm" fw={600}>{item.name}</Text><Text size="xs" c="dimmed" mt={4}>{item.location}</Text></div><span className={s.evidenceNumber}>{index+1}</span></Group></button>)}</Stack><div className={s.quote}><IconQuote size={25} stroke={1.4}/><Text mt="md" lh={1.85}>{evidence[selected].text}</Text><Text mt="lg" size="xs" fw={600} c="dimmed">{evidence[selected].location}</Text></div><div className={s.evidenceFoot}><Text size="xs" c="dimmed">Evidence helps you verify an answer. AI can still make mistakes.</Text></div></Paper><Paper className={s.noteCard}><IconInfoCircle size={19}/><Text size="sm">New to this workspace? Start by asking about a specific topic, decision, or conversation.</Text></Paper></aside></div>
  </>;
}
