import React, { useState } from 'react';
import { Accordion, ActionIcon, Alert, Badge, Button, FileInput, Group, Menu, Modal, Paper, SegmentedControl, Select, Stack, Table, Tabs, Text, TextInput, Title } from '@mantine/core';
import { IconPlus, IconArrowUpRight, IconArrowLeft, IconSearch, IconDots, IconRefresh, IconTrash, IconUpload, IconLink, IconBrandYoutube, IconCheck, IconArrowRight, IconInfoCircle, IconFileText } from '@tabler/icons-react';
import { PageTitle, SourceIcon, Status } from './shared.jsx';
import { sources, passages } from './fixtures.js';
import s from './workspace.module.css';

export default function Library({ route, addSource, navigate, notify }) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('All sources');
  const [confirm, setConfirm] = useState(null);
  const [removed, setRemoved] = useState([]);
  const [retrying, setRetrying] = useState([]);
  const active = sources.find(source => source.id === route.split('/')[1]);
  if (active) return <SourceDetail source={active} navigate={navigate} notify={notify}/>;
  const present = sources.filter(source => !removed.includes(source.id));
  const visible = present.filter(source => source.name.toLowerCase().includes(search.toLowerCase()) && (filter === 'All sources' || source.type === filter));
  function reprocess(source) { setRetrying([...retrying, source.id]); notify(`“${source.name}” is marked Processing in this preview.`); }
  return <>
    <PageTitle eyebrow="THE STARTING POINT" title="Your knowledge, together." description="A home for the sources behind your next good idea."><Button leftSection={<IconPlus size={18}/>} onClick={addSource}>Add source</Button></PageTitle>
    <section className={s.libraryIntro} aria-label="Workspace summary"><div><Badge variant="light" color="workspace" mb={18}>ATLAS LAUNCH / RESEARCH SPACE</Badge><Title order={2}>From scattered files<br/>to a shared understanding.</Title><Text c="dimmed" mt={12} maw={380}>Ask across your documents, visuals, and conversations. Every answer starts with your sources.</Text><Button mt={22} variant="white" color="workspace" rightSection={<IconArrowUpRight size={17}/>} onClick={() => navigate('ask')}>Ask your workspace</Button></div><div className={s.knowledgeArt} aria-hidden="true"><div className={s.artOrbit}/><div className={`${s.artCard} ${s.artBack}`}><SourceIcon type="Audio"/><span>Conversations</span><div className={s.waveform}>{Array.from({length: 18}, (_, i) => <i key={i} style={{height: `${12 + (i * 17 % 30)}px`}}/>)}</div></div><div className={`${s.artCard} ${s.artFront}`}><SourceIcon type="Document"/><span>Ideas, connected.</span><div className={s.artLines}><i/><i/><i/></div><Badge variant="light" color="workspace" leftSection={<IconCheck size={12}/>}>Ready to explore</Badge></div><span className={s.artSpark}>✦</span></div></section>
    <div className={s.stats}>{[[present.length,'Total sources','Across six formats'],[present.filter(x => x.status === 'Ready').length,'Ready to ask','Indexed and searchable'],[1,'Processing','Team kickoff.mp4'],[1,'Needs attention','Automatic retry scheduled']].map(([number,label,detail]) => <Paper key={label} className={s.stat}><Text size="sm" c="dimmed">{label}</Text><Group align="baseline" gap={10} mt={7}><Text className={s.statNumber}>{number.toString().padStart(2,'0')}</Text><Text size="xs" c="dimmed">{detail}</Text></Group></Paper>)}</div>
    <Paper className={s.sourcePanel}><div className={s.panelHeading}><Group><Title order={3}>Source library</Title><Badge color="gray" variant="light">{present.length}</Badge></Group><ActionIcon variant="subtle" color="ink" aria-label="Refresh sources" onClick={() => notify('Sample source list refreshed.')}><IconRefresh size={18}/></ActionIcon></div>
      <div className={s.sourceToolbar}><TextInput aria-label="Search sources" placeholder="Find a source by name…" leftSection={<IconSearch size={17}/>} value={search} onChange={e => setSearch(e.target.value)} className={s.sourceSearch}/><Select aria-label="Source type" data={['All sources','Document','Audio','Image','Video','YouTube','Web page']} value={filter} onChange={value => setFilter(value || 'All sources')} w={166} allowDeselect={false}/><Text size="xs" c="dimmed" className={s.resultCount}>{visible.length} sources</Text></div>
      <Table.ScrollContainer minWidth={680}><Table verticalSpacing="md" horizontalSpacing="lg" className={s.sourceTable}><Table.Thead><Table.Tr><Table.Th>NAME</Table.Th><Table.Th>STATUS</Table.Th><Table.Th>ADDED</Table.Th><Table.Th><span className={s.srOnly}>Actions</span></Table.Th></Table.Tr></Table.Thead><Table.Tbody>{visible.map(source => <Table.Tr key={source.id}><Table.Td><button className={s.sourceName} onClick={() => navigate(`source/${source.id}`)}><SourceIcon type={source.type}/><span><strong>{source.name}</strong><small>{source.detail}</small></span></button></Table.Td><Table.Td><Status value={retrying.includes(source.id) ? 'Processing' : source.status}/></Table.Td><Table.Td><Text size="sm" c="dimmed">{source.date}</Text></Table.Td><Table.Td><Menu position="bottom-end"><Menu.Target><ActionIcon variant="subtle" color="ink" aria-label={`Actions for ${source.name}`}><IconDots size={18}/></ActionIcon></Menu.Target><Menu.Dropdown><Menu.Item onClick={() => navigate(`source/${source.id}`)}>View details</Menu.Item><Menu.Item leftSection={<IconRefresh size={15}/>} disabled={source.status === 'Processing' || retrying.includes(source.id)} onClick={() => reprocess(source)}>Reprocess</Menu.Item><Menu.Item color="red" leftSection={<IconTrash size={15}/>} onClick={() => setConfirm(source)}>Delete source</Menu.Item></Menu.Dropdown></Menu></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>
      <div className={s.mobileSourceList}>{visible.map(source => <div className={s.mobileSource} key={source.id}><button className={s.sourceName} onClick={() => navigate(`source/${source.id}`)}><SourceIcon type={source.type}/><span><strong>{source.name}</strong><small>{source.detail}</small></span></button><Group justify="space-between" mt="md"><Status value={retrying.includes(source.id) ? 'Processing' : source.status}/><Menu position="bottom-end"><Menu.Target><ActionIcon variant="subtle" color="ink" size="lg" aria-label={`Mobile actions for ${source.name}`}><IconDots size={20}/></ActionIcon></Menu.Target><Menu.Dropdown><Menu.Item onClick={() => navigate(`source/${source.id}`)}>View details</Menu.Item><Menu.Item disabled={source.status === 'Processing' || retrying.includes(source.id)} onClick={() => reprocess(source)}>Reprocess</Menu.Item><Menu.Item color="red" onClick={() => setConfirm(source)}>Delete source</Menu.Item></Menu.Dropdown></Menu></Group></div>)}</div>
      {!visible.length && <div className={s.empty}><IconSearch size={32}/><Title order={3}>No matching sources</Title><Text c="dimmed">Try another name or change the type filter.</Text><Button variant="subtle" mt="sm" onClick={() => {setSearch('');setFilter('All sources');}}>Clear filters</Button></div>}
      <div className={s.panelFoot}><IconInfoCircle size={15}/><span>Only ready sources are available for questions. Processing status updates appear in Activity.</span></div>
    </Paper>
    <Modal opened={Boolean(confirm)} onClose={() => setConfirm(null)} title="Delete this source?"><Text mb="lg">{confirm?.name} and its searchable knowledge will be removed from this workspace.</Text><Group justify="flex-end"><Button variant="default" onClick={() => setConfirm(null)}>Keep source</Button><Button color="red" onClick={() => {setRemoved([...removed,confirm.id]);setConfirm(null);}}>Delete source</Button></Group></Modal>
  </>;
}

export function AddSource({ opened, onClose, notify }) {
  const [tab, setTab] = useState('file');
  const [file, setFile] = useState(null);
  const [url, setUrl] = useState('');
  const [kind, setKind] = useState('Document');
  const [error, setError] = useState('');
  function submit() {
    if (tab === 'file' && !file) {setError('Choose a file to continue.');return;}
    if (tab !== 'file') { try {const parsed = new URL(url); if (!['http:','https:'].includes(parsed.protocol)) throw Error();} catch {setError('Enter a complete HTTP or HTTPS URL.');return;} }
    onClose(); setError(''); notify('Source submission demonstrated. This prototype uses sample data and does not upload files or call providers.');
  }
  return <Modal opened={opened} onClose={onClose} size={640} title={<Text fw={650} size="lg">Add a source</Text>}><Text c="dimmed" mb="lg">Bring something useful into Atlas launch.</Text><Tabs value={tab} onChange={value => {setTab(value);setError('');}}><Tabs.List grow><Tabs.Tab value="file" leftSection={<IconUpload size={17}/>}>Upload file</Tabs.Tab><Tabs.Tab value="web" leftSection={<IconLink size={17}/>}>Web page</Tabs.Tab><Tabs.Tab value="youtube" leftSection={<IconBrandYoutube size={17}/>}>YouTube</Tabs.Tab></Tabs.List></Tabs>
    <Stack mt="lg" gap="lg">{tab === 'file' ? <><div className={s.uploadWell}><span className={s.uploadCircle}><IconUpload size={29} stroke={1.5}/></span><Title order={3}>A little context goes a long way.</Title><Text size="sm" c="dimmed" maw={360} mx="auto" mt={8}>Choose a document, image, audio recording, or video from your device.</Text></div><Select label="Source type" data={['Document','Audio','Image','Video']} value={kind} onChange={setKind} allowDeselect={false}/><FileInput label="File" placeholder="Browse files" leftSection={<IconFileText size={17}/>} value={file} onChange={setFile} clearable/><Text size="xs" c="dimmed">Images up to 10 MB · Videos up to 20 MB · Request limit 25 MB.<br/>PDF, Word, Excel, PowerPoint, TXT, WAV, MP3, MP4, AVI, JPG, PNG, WebP and supported video formats.</Text></> : <><TextInput label={tab === 'youtube' ? 'YouTube video URL' : 'Public page URL'} placeholder={tab === 'youtube' ? 'https://www.youtube.com/watch?v=…' : 'https://example.com/article'} value={url} onChange={e => setUrl(e.target.value)}/><Alert icon={<IconInfoCircle size={18}/>} color="workspace">{tab === 'youtube' ? 'We analyze the video’s visuals and spoken conversation. Use a video the provider can access.' : 'We extract the readable content of a public HTML or text page. Pages requiring sign-in are not supported.'}</Alert></>}{error && <Alert color="red">{error}</Alert>}<Group justify="space-between" className={s.modalFooter}><Text size="xs" c="dimmed">Destination: Atlas launch</Text><Group><Button variant="default" onClick={onClose}>Cancel</Button><Button rightSection={<IconArrowRight size={16}/>} onClick={submit}>{tab === 'file' ? 'Add and process' : 'Import source'}</Button></Group></Group></Stack></Modal>;
}

function SourceDetail({ source, navigate, notify }) {
  const isAudio = ['Audio','Video','YouTube'].includes(source.type);
  return <><Button variant="subtle" leftSection={<IconArrowLeft size={16}/>} px={0} mb="lg" onClick={() => navigate('library')}>Back to library</Button><div className={s.detailHeading}><Group wrap="nowrap"><SourceIcon type={source.type} large/><div><Text className={s.eyebrow}>SOURCE DETAILS</Text><Title order={1}>{source.name}</Title><Text c="dimmed" mt={7}>{source.detail} · Added {source.date.toLowerCase()}</Text></div></Group><Status value={source.status}/></div>
    {source.status === 'Needs attention' && <Alert color="orange" title="We couldn’t reach this website" mb="lg">Your source is saved. An automatic retry is scheduled. You can also try reprocessing now.</Alert>}
    <div className={s.detailGrid}><Paper className={s.readingPanel}><div className={s.panelHeading}><Title order={3}>{isAudio ? 'Conversation transcript' : 'Source overview'}</Title><Badge variant="light" color="gray">{isAudio ? 'Sample extract' : source.type}</Badge></div><div className={s.transcriptIntro}><Text size="sm" c="dimmed">{isAudio ? 'Customer research · English · Timed evidence' : source.context}</Text><Title order={2} mt="lg">{isAudio ? 'Making the first session useful' : 'A clearer path to launch'}</Title><Text c="dimmed" mt="sm">{isAudio ? 'An interview about finding useful answers, understanding sources, and building trust.' : 'Positioning, launch milestones, and the decisions behind the Atlas release.'}</Text></div>{isAudio ? <div className={s.transcript}>{passages.map(p => <div key={p.time} className={s.transcriptRow} data-active={p.active}><span>{p.time}</span><p>{p.text}</p></div>)}</div> : <div className={s.transcriptIntro}><Text lh={1.9}>Atlas brings documents, media, and conversations into a workspace where people can ask clear questions and inspect the evidence behind each answer.</Text><Text mt="lg" lh={1.9}>For launch, focus on a useful first answer, visible source status, and a short path from an answer to its supporting passage.</Text></div>}<div className={s.panelFoot}><IconInfoCircle size={16}/><span>This is a sample content preview. Persisted transcript and document previews require an additional content API.</span></div></Paper><Stack><Paper p="lg"><Text className={s.eyebrow}>WORK WITH THIS SOURCE</Text><Title order={3} mt="sm">Make the next connection.</Title><Text size="sm" c="dimmed" mt="sm" mb="lg">Ask a question across all ready sources in this workspace.</Text><Button fullWidth rightSection={<IconArrowUpRight size={17}/>} onClick={() => navigate('ask')}>Ask workspace</Button><Button fullWidth mt="sm" variant="default" disabled={source.status === 'Processing'} leftSection={<IconRefresh size={16}/>} onClick={() => notify('Reprocessing would create a job for this source.')}>Reprocess source</Button></Paper><Paper p="lg"><Text fw={600} mb="md">Source information</Text><div className={s.metadata}><span>Type</span><strong>{source.type}</strong><span>Status</span><strong>{source.status}</strong><span>Workspace</span><strong>Atlas launch</strong><span>Added</span><strong>{source.date}</strong></div><Accordion mt="lg" variant="contained"><Accordion.Item value="technical"><Accordion.Control>Technical details</Accordion.Control><Accordion.Panel><Text size="xs">Source ID: demo-{source.id}<br/>Recovery: {source.status === 'Needs attention' ? 'Scheduled' : 'Completed'}<br/>Provider, storage checksum, and retry details belong here when returned by the API.</Text></Accordion.Panel></Accordion.Item></Accordion></Paper></Stack></div></>;
}
