import React, { useState } from 'react';
import { Alert, Button, Group, Paper, PasswordInput, Stack, Text, TextInput, Title } from '@mantine/core';
import { IconArrowRight, IconCheck } from '@tabler/icons-react';
import { Brand, SourceIcon } from './shared.jsx';
import s from './workspace.module.css';

export default function Login({ onEnter }) {
  const [register,setRegister] = useState(false);
  return <div className={s.login}><section className={s.loginStory}><Brand light/><div><Text className={s.loginEyebrow}>YOUR IDEAS HAVE COMPANY.</Text><h1>Bring the pieces.<br/><em>Find the picture.</em></h1><Text c="#bed0cc" size="lg" maw={430} lh={1.8}>Documents, conversations, images, and videos. One place to understand what they mean together.</Text><div className={s.loginCards}>{['Document','Audio','Image'].map((type,index) => <div key={type} style={{transform:`rotate(${index===1?4:-4}deg) translateY(${index===1?-12:0}px)`}}><SourceIcon type={type}/><Text c="white" mt="lg" fw={600}>{['A useful idea','A new perspective','A different angle'][index]}</Text><div className={s.loginCardLines}><i/><i/><i/></div></div>)}</div></div><Text size="sm" c="#bed0cc">Gather. Understand. Create.</Text></section><main className={s.loginForm}><Paper withBorder={false} bg="transparent" p={0}><Text className={s.eyebrow}>AI WORKSPACE</Text><Title order={1} mt="sm">{register?'Make room for your ideas.':'Good to have you back.'}</Title><Text c="dimmed" mt="sm" mb={30}>{register?'Create your personal workspace.':'Sign in and pick up where you left off.'}</Text><Stack gap="md">{register && <TextInput label="Your name" placeholder="Alex Chen" autoComplete="name"/>}<TextInput label="Email address" placeholder="you@example.com" autoComplete="username"/><PasswordInput label="Password" placeholder={register?'At least 12 characters':'Enter your password'} autoComplete={register?'new-password':'current-password'}/>{register && <Text size="xs" c="dimmed">Use at least 12 characters, up to 72 UTF-8 bytes.</Text>}<Button rightSection={<IconArrowRight size={17}/>} onClick={onEnter}>Open design preview</Button></Stack><Group gap={5} mt="lg"><Text size="sm" c="dimmed">{register?'Already have an account?':'New to AI Workspace?'}</Text><Button size="compact-sm" variant="subtle" onClick={()=>setRegister(!register)}>{register?'Sign in':'Create an account'}</Button></Group><Text size="xs" c="dimmed" mt={35} lh={1.8}>Prototype only. These fields do not authenticate or transmit data. The production screen will use the existing registration and sign-in flow.</Text></Paper><Text className={s.loginFooter}>A little context. A lot more possibility.</Text></main></div>;
}
